config/routes.rb
Rails.application.routes.draw do
  root to: 'front_page#front_page'

  get 'search', to: 'front_page#search'

  resources :authors
  resources :books

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates :name, presence: true, uniqueness: true
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  validates :title, :author, :year, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from StandardError do |exception|
    redirect_to root_path, alert: 'An error occurred.'
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(name: params[:author][:name].strip)
    
    if @author.save
      redirect_to @author, notice: 'Author was successfully created.'
    else
      render :new
    end
  end
  
  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    new_name = params[:author][:name].strip
    existing_author = Author.find_by(name: new_name)
  
    if existing_author && existing_author.id != @author.id
      redirect_to @author, notice: 'Author already exists'
    else
      if @author.update(name: new_name)
        redirect_to @author, notice: 'Author was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    if @author.books.exists?
      redirect_to authors_url, notice: "Author cannot be deleted because they are associated with one or more books. Remove the books first."
    else
      @author.destroy
      redirect_to authors_url, notice: "Author was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  def search
    @books = Book.where('title LIKE ?', "%#{params[:query]}%")
  end
  # POST /books or /books.json
  # app/controllers/books_controller.rb

  def create
    author_name = params[:book].delete(:author_name)&.strip
    author = Author.find_or_create_by!(name: author_name)
    @book = Book.new(book_params.merge(author_id: author.id))

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end
  
  def update
    author_name = params[:book].delete(:author_name)&.strip
    author = Author.find_or_create_by!(name: author_name)
    
    if @book.update(book_params.merge(author_id: author.id))
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  private

    def book_params
      params.require(:book).permit(:title, :pages, :image_link, :author_id, :year, :author_name)
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController
  def front_page
  end

  def search
    if params[:type] == 'book'
      @books = Book.where('title LIKE ?', "%#{params[:query]}%")
      if @books.present?
        redirect_to book_url(@books.first)
        return
      end
    elsif params[:type] == 'author'
      @authors = Author.where('name LIKE ?', "%#{params[:query]}%")
      if @authors.present?
        redirect_to author_url(@authors.first)
        return
      end
    end
    render :front_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <% if controller.action_name == 'show' %>
    <h3>Author: <%= author.name %></h3>
    <ul>
      <% author.books.each do |book| %>
        <li><%= link_to book.title, book_path(book) %></li>
      <% end %>
    </ul>
  <% else %>
    <h3>Author: <%= link_to author.name, author %></h3>
  <% end %>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: author.name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>

<div id="authors">
  <% @authors.each do |author| %>
    <div class="author-card">
      <h2><%= author.name %></h2>
      <p>
        <%= link_to "Show this author", author %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New author", new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <% if controller.action_name == 'show' %>
    <%# Larger image and all details for the show page %>
    <%= image_tag(book.image_link.presence || "https://placehold.co/300x450?text=No+cover", alt: "#{book.title} thumbnail", width: "300", height: "450") %>
    <h1><%= book.title %></h1>
    <p>Author: <%= link_to book.author.name, author_path(book.author) %></p>
    <p>Year: <%= book.year %></p>
    <p>Pages: <%= book.pages %></p>
    <%# Add other details here %>
  <% else %>
    <%# Smaller image and limited details for index and other pages %>
    <%= image_tag(book.image_link.presence || "https://placehold.co/100x150?text=No+cover", alt: "#{book.title} thumbnail", width: "100", height: "150") %>
    <h2><%= book.title %></h2>
    <p>Author: <%= book.author.name %></p>
  <% end %>
  <p><%= link_to "Show this book", book %></p>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :pages %>
    <%= form.number_field :pages %>
  </div>

  <div>
    <%= form.label :image_link %>
    <%= form.text_field :image_link %>
  </div>

  <div>
    <%= form.label :author_name, "Author" %>
    <%= form.text_field :author_name %>
  </div>

  <div>
    <%= form.label :publication_year %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <div class="book-card">
      <% if book.image_link.present? %>
        <%= image_tag(book.image_link, alt: "#{book.title} thumbnail", width: "100", height: "150") %>
      <% else %>
        <%= image_tag("https://placehold.co/100x150?text=No+cover", alt: "#{book.title} thumbnail", width: "100", height: "150") %>
      <% end %>
      <h2><%= book.title %></h2>
      <p>Author: <%= book.author.name %></p>
      <p>
      <%= link_to "Show this book", book %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/front_page/front_page.html.erb
<div class="front-page-container">

  <% if @books.present? %>
  <h1>Books</h1>
  <% @books.each do |book| %>
    <%= link_to book.title, book %>
  <% end %>
  <% end %>

  <% if @authors.present? %>
  <h1>Authors</h1>
  <% @authors.each do |author| %>
    <%= link_to author.name, author %>
  <% end %>
  <% end %>
  <h2>Roger Consul</h2>
  <p>
    Connect with me on <%= link_to 'LinkedIn', 'https://linkedin.com/in/rogerconsul', target: '_blank' %>.
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Logistic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Books', books_path %></li>
        <li><%= link_to 'Authors', authors_path %></li>
        <li>
          <%= form_with url: search_path, method: :get, local: true do |form| %>
            <%= form.text_field :query, placeholder: "Search" %>
            <%= form.radio_button :type, "book", checked: true %> Book
            <%= form.radio_button :type, "author" %> Author
            <%= form.submit "Search" %>
          <% end %>
        </li>
        <li><%= link_to "New book", new_book_path %></li>
        <li><%= link_to "New author", new_author_path %></li>
      </ul>
    </nav>
  
    <%= yield %>
  </body>
</html>